@startuml
left to right direction
actor "User" as user
actor "Database" as db <<System Actor>>

package "Messenger Application" {
  usecase "Register" as UC1
  usecase "Login" as UC2
  usecase "Add Contact" as UC3
  usecase "Send Message" as UC4
  usecase "Initiate Audio Call" as UC5
  usecase "Initiate Video Call" as UC6
  usecase "Accept/Reject Call" as UC7
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5
user --> UC6
user --> UC7

UC1 ..> db : <<include>>
UC2 ..> db : <<include>>
UC3 ..> db : <<include>>
UC4 ..> db : <<include>>

@enduml
